api_retries: 3
api_timeout: 5s
history: # history klines are downloaded from Binance only
  do_history: true
  interval: 1w
  spot_only: true
  quote_only: true
  quotes: [USDT]
  tradable_only: false
  fiat_removed: true
  stablecoins_removed: true
trades:
  do_trades: [binance, kraken]
  # following settings are relevant for Binance trades only, kraken downloads trades without settings
  quote_only: true
  quotes: [EUR]
  limit: 1000
  recvwindow: 60000
withdrawals:
  do_withdrawals: [binance, kraken]
  # following settings are relevant for Binance withdrawals only, kraken downloads withdrawals without settings
  status: 6
  limit: 1000
  recvwindow: 60000
  ts_start: "2023-01-01"
  ts_window: 60d
api_clients:
  binance:
    url: https://api.binance.com
    limit_requests: 1200
    limit_period: 1m
    limit_status_codes: [429, 418, 403]
  coinmarketcap:
    url: https://pro-api.coinmarketcap.com
    limit_requests: 30
    limit_period: 1m
    limit_status_codes: [429]
  kraken:
    url: https://api.kraken.com
    limit_requests: 1
    limit_period: 1s
    limit_status_codes: []
  