interval: 1w
api_retries: 3
api_timeout: 5s
history:
# relevant for Binanace klines only
  spot_only: true
  quote_only: true
  quotes: [USDT]
  tradable_only: false
  fiat_removed: true
  stablecoins_removed: true
trades:
# relevant for Binanace trades only at the moment
  quote_only: true
  quotes: [EUR]
  limit: 1000
  recvwindow: 60000
api_clients:
  binance:
    url: https://api.binance.com/api/v3
    limit_requests: 1200
    limit_period: 1m
    limit_status_codes: [429, 418, 403]
  coinmarketcap:
    url: https://pro-api.coinmarketcap.com
    limit_requests: 30
    limit_period: 1m
    limit_status_codes: [429]
  kraken:
    url: https://api.kraken.com
    limit_requests: 1
    limit_period: 1s
    limit_status_codes: []
  